# Generated by Django 4.1.dev20220210102451 on 2022-03-30 22:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200, null=True)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('recipe_description', models.TextField(null=True)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
