# Generated by Django 4.1.dev20220210102451 on 2022-03-20 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_text',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='publisher',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
