# Generated by Django 4.1.dev20220210102451 on 2022-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0003_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='media/images/default_image.png', null=True, upload_to='images/'),
        ),
    ]
