# Generated by Django 4.1.dev20220210102451 on 2022-04-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0003_recipe_recipe_image_alter_recipe_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_of_recipe',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
