# Generated by Django 4.1.dev20220210102451 on 2022-04-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0004_remove_recipe_recipe_image_recipe_image_of_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='publisher',
        ),
    ]
