# Generated by Django 4.1.dev20220210102451 on 2022-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0004_alter_recipe_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default=''),
        ),
    ]
