# Generated by Django 4.1.dev20220210102451 on 2022-04-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WOMbasic', '0005_rename_publisher_recipe_publisher_id'),
    ]

    operations = [

        migrations.AddField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
