# Generated by Django 4.1.dev20220210102451 on 2022-04-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0006_remove_recipe_publisher_id_recipe_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='publisher',
        ),
    ]
