# Generated by Django 4.1.dev20220210102451 on 2022-04-03 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WOMbasic', '0007_remove_recipe_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_of_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
