# Generated by Django 4.1.dev20220210102451 on 2022-04-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WOMbasic', '0008_remove_recipe_image_of_recipe_recipe_publisher_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
