# Generated by Django 4.1.dev20220210102451 on 2022-04-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0010_recipe_recipe_image_alter_recipe_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='/media/images/default_image.png', upload_to='media/images/'),
        ),
    ]
