# Generated by Django 4.1.dev20220210102451 on 2022-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0012_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forked',
            field=models.BooleanField(default=False),
        ),
    ]
