# Generated by Django 4.1.dev20220210102451 on 2022-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0013_recipe_forked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forked_form',
            field=models.IntegerField(default=1),
        ),
    ]
