# Generated by Django 4.1.dev20220210102451 on 2022-04-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0014_recipe_forked_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='forked_form',
            new_name='forked_from',
        ),
    ]
