# Generated by Django 4.1.dev20220210102451 on 2022-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0015_rename_forked_form_recipe_forked_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='forked_from',
            field=models.TextField(default=''),
        ),
    ]
