# Generated by Django 4.1.dev20220210102451 on 2022-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0016_alter_recipe_forked_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forked_fromId',
            field=models.IntegerField(default=1),
        ),
    ]
