# Generated by Django 4.1.dev20220210102451 on 2022-04-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0014_alter_recipe_likes'),
        ('WOMbasic', '0017_recipe_forked_fromid'),
    ]

    operations = [
    ]
