# Generated by Django 4.0.2 on 2022-04-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0019_merge_0005_ingredients_0018_merge_20220416_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
