# Generated by Django 4.0.2 on 2022-04-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0021_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='recipe',
        ),
    ]
