# Generated by Django 4.1.dev20220210102451 on 2022-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0022_rename_post_comment_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default='', verbose_name='Step-by-step Instructions'),
        ),
    ]
