# Generated by Django 4.1.dev20220210102451 on 2022-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0023_recipe_ingredients_alter_recipe_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default='', verbose_name='Step-by-Step Instructions'),
        ),
    ]
