# Generated by Django 4.1.dev20220210102451 on 2022-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0024_alter_recipe_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='images/default_image.png', null=True, upload_to='images/', verbose_name='Picture of Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=200, verbose_name='Name of Recipe'),
        ),
    ]
