# Generated by Django 4.1.dev20220210102451 on 2022-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOMbasic', '0025_alter_recipe_recipe_image_alter_recipe_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_steps',
            field=models.TextField(default='', verbose_name='Step-by-Step Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default='', verbose_name='Brief Description'),
        ),
    ]
